# Generated by Django 5.1.7 on 2025-04-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=50)),
                ('cantidad_de_peces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='PurezaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purezas_agua', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purezas_agua', to='peceras.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='NivelOxigeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_oxigeno', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_oxigeno', to='peceras.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_agua', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_agua', to='peceras.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='peceras.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='CorrienteElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrientes_electricas', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrientes_electricas', to='peceras.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
                ('fk_pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturas', to='peceras.pecera')),
                ('fk_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturas', to='peceras.sensor')),
            ],
        ),
    ]
