# Generated by Django 5.2 on 2025-05-31 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.cliente')),
                ('tamaño', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peceras.tamaño')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosCalidadAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calidad', models.FloatField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosFlujoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('flujo', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.BooleanField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosNivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('porcentaje', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosNivelOxigenoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('oxigeno_disuelto', models.FloatField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('sensor', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peceras.pecera')),
            ],
        ),
    ]
