# Generated by Django 5.2 on 2025-06-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tamano', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosCalidadAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.FloatField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_calidad', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosFlujoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_flujo', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.BooleanField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_movimiento', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosNivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.IntegerField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_nivelagua', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosNivelOxigenoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.FloatField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_oxigeno', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrosTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('data', models.FloatField()),
                ('pecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_temperatura', to='peceras.pecera')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='peceras.tiposensor')),
            ],
        ),
    ]
